production:
  debug: false
  gateway_host: 'http://gateway.pooulcloud.cn'
  key_dir: '/home/prod/szpl/current/cert'
  home_dir: '/home/prod/szpl/current'
  biz_send:
    host: '172.18.183.142'
    prg:  'orders_common'

development:
  debug: true


test:
  debug: true

